// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `code_for`, `context`, `internal`, `invalid_argument`, `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

/// The kind of failure, for a caller to `switch` on.
///
/// Codes are added, removed or renamed only in a major release, so a `switch`
/// that lists every code keeps compiling through minor and patch releases. A
/// condition libsignal introduces in between is given the closest existing
/// code. The order of the codes is part of the bridge between Dart and the
/// native library as well, which is another reason it moves only in a major.
enum LibSignalErrorCode {
  /// A caller-supplied value is out of range or malformed: a device id
  /// outside 1–127, an AES-GCM-SIV key or nonce of the wrong length, an HKDF
  /// output length over the limit, an empty destination list.
  invalidArgument,

  /// The operation cannot succeed in the object's current state, for example
  /// a session record with no current session.
  invalidState,

  /// An invariant inside this package or libsignal did not hold. Not caused
  /// by the input; worth reporting as a bug.
  internalError,

  /// Bytes that should hold a serialized message, record or certificate do
  /// not parse. A session record that does not parse is `invalidSession`
  /// instead.
  protobufError,

  /// The message claims a protocol version too old to be read. That byte is
  /// checked before the message is authenticated, so anyone can produce this.
  legacyCiphertextVersion,

  /// The message claims a ciphertext version this libsignal does not know. A
  /// sender on a newer protocol version produces it, but so does anyone who
  /// changes that byte: it is checked before the message is authenticated.
  unknownCiphertextVersion,

  /// A message or sealed-sender envelope claims a version this libsignal does
  /// not know, or a sender-key message's version does not match the stored
  /// sender-key state.
  unrecognizedMessageVersion,

  /// The message is malformed, failed authentication, or does not belong to
  /// the context the caller named: too short, a bad MAC, a ciphertext that
  /// does not decrypt, a sealed-sender envelope that does not open, a
  /// sender-key distribution message for a different distribution id. A group
  /// message whose signature does not verify is `invalidSignature` instead.
  invalidMessage,

  /// A sealed-sender message names this very device as its sender.
  sealedSenderSelfSend,

  /// A public, private, Kyber or MAC key is malformed, of the wrong type or
  /// length, or unusable for the operation (for example a low-order point).
  /// An AES-GCM-SIV key of the wrong length is `invalidArgument`.
  invalidKey,

  /// A signature did not verify, for example on a pre-key bundle or a group
  /// message.
  invalidSignature,

  /// The two fingerprints being compared were made with different versions.
  fingerprintVersionMismatch,

  /// Bytes that should hold a scannable fingerprint do not parse.
  fingerprintParsingError,

  /// An identity key presented for an address differs from the one stored
  /// for it. On a pre-key message the key is the one the message carries,
  /// compared before anything in the message is authenticated, so this code
  /// alone does not show that the peer's key changed.
  untrustedIdentity,

  /// A message refers to a pre-key, signed pre-key or Kyber pre-key id that
  /// the store does not hold.
  invalidKeyIdentifier,

  /// There is no session, or no sender-key state, to use for this address,
  /// or for the chain a group message names.
  sessionNotFound,

  /// A session's stored registration id is invalid, for example wider than
  /// the 14 bits a multi-recipient sealed-sender message carries.
  invalidRegistrationId,

  /// A session record is malformed, including one given to
  /// `SessionRecord.deserialize`.
  invalidSession,

  /// A stored sender-key record holds no state to use.
  invalidSenderKeySession,

  /// The session's chain has moved past the counter this message carries and
  /// holds no key for it any more, which normally means the message was
  /// decrypted before. Decided before the message is authenticated.
  duplicatedMessage,

  /// A sender certificate did not validate: expired at the given time, its
  /// server certificate not signed by the trust root or revoked, the sender
  /// certificate not signed by that server certificate, or a reference to a
  /// server certificate that is not a known one.
  ///
  /// This says nothing about who sent the message. The certificate in a
  /// sealed-sender envelope is chosen by whoever sealed it, and anyone who
  /// knows your public identity key can seal one that fails here. Treat it as
  /// a rejected message: log it, and never let it change settings such as the
  /// trust root or the clock, or make you stop sending sealed messages.
  /// libsignal's own sealed-sender decrypt reports this case as an invalid
  /// message; this package gives it a code of its own so that a log can tell a
  /// certificate problem from a damaged envelope.
  verificationFailure,
}

/// Thrown by a call into the native library that fails.
///
/// Decide what to do from `code`, which changes only in a major release.
/// `message` explains the failure for a log or a bug report, in libsignal's
/// wording where libsignal raised it, and can change in any release.
/// `toString()` returns `LibSignalException(<code>): <message>`.
///
/// Some failures arrive as other types:
/// - A store callback that throws cannot be reported through this type,
///   because the store interfaces cannot return an error across the bridge.
///   The call panics instead. Every call that takes store callbacks is
///   asynchronous, so on the web it never completes (see below).
/// - A panic in the native code is `flutter_rust_bridge`'s `PanicException`
///   on native platforms. On the web the WebAssembly module traps: a
///   synchronous call then throws `PanicException`, and an asynchronous call
///   never completes.
/// - A call on an object after its `dispose()` throws `flutter_rust_bridge`'s
///   `DroppableDisposedException`. flutter_rust_bridge does not export that
///   type, so catch it as `FrbException`.
/// - Checks made in Dart before the native call throw `ArgumentError` or
///   `StateError`.
///
/// `FrbException` and `PanicException` come from
/// `package:flutter_rust_bridge/flutter_rust_bridge.dart`; this package does
/// not re-export them.
class LibSignalException implements FrbException {
  /// What kind of failure this is. Stable across minor releases.
  final LibSignalErrorCode code;

  /// Details for a log; the wording can change in any release.
  final String message;

  const LibSignalException({required this.code, required this.message});

  @override
  String toString() => 'LibSignalException(${code.name}): $message';

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibSignalException &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}
