// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the libsignal library.
///
/// With the pure Rust implementation using libsignal-protocol crate,
/// this function is no longer required but kept for API compatibility.
/// The library_path parameter is ignored.
void initLibsignal({required String libraryPath}) =>
    RustLib.instance.api.crateApiInitInitLibsignal(libraryPath: libraryPath);

/// Check if the libsignal library is initialized.
///
/// With the pure Rust implementation, this always returns true.
bool isLibsignalInitialized() =>
    RustLib.instance.api.crateApiInitIsLibsignalInitialized();
