// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_native`, `from_native`, `from_native`, `native`, `native`, `native`

/// Sign an alternate identity key using separate keys.
///
/// This is a standalone version that doesn't require an IdentityKeyPair.
Uint8List identityKeypairSignAlternateIdentityRaw({
  required PublicKey publicKey,
  required PrivateKey privateKey,
  required PublicKey otherIdentity,
}) => RustLib.instance.api.crateApiKeysIdentityKeypairSignAlternateIdentityRaw(
  publicKey: publicKey,
  privateKey: privateKey,
  otherIdentity: otherIdentity,
);

/// Serialize an identity key pair from separate keys.
///
/// This is a standalone version that doesn't require an IdentityKeyPair.
Uint8List identityKeypairSerializeRaw({
  required PublicKey publicKey,
  required PrivateKey privateKey,
}) => RustLib.instance.api.crateApiKeysIdentityKeypairSerializeRaw(
  publicKey: publicKey,
  privateKey: privateKey,
);

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IdentityKeyPair>>
abstract class IdentityKeyPair implements RustOpaqueInterface {
  /// Deserialize an identity key pair from bytes.
  ///
  /// # Security
  /// The input bytes are securely zeroized after deserialization.
  static IdentityKeyPair deserialize({required List<int> bytes}) =>
      RustLib.instance.api.crateApiKeysIdentityKeyPairDeserialize(bytes: bytes);

  /// Create an identity key pair from existing keys.
  static IdentityKeyPair fromKeys({
    required PrivateKey privateKey,
    required PublicKey publicKey,
  }) => RustLib.instance.api.crateApiKeysIdentityKeyPairFromKeys(
    privateKey: privateKey,
    publicKey: publicKey,
  );

  /// Generate a new identity key pair.
  static IdentityKeyPair generate() =>
      RustLib.instance.api.crateApiKeysIdentityKeyPairGenerate();

  /// Get the private key as serialized bytes.
  ///
  /// # Security
  /// The returned bytes contain sensitive private key material.
  /// The caller is responsible for securely zeroing these bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side to ensure automatic zeroing.
  Uint8List get privateKey;

  /// Get the public key as serialized bytes.
  Uint8List get publicKey;

  /// Serialize this identity key pair.
  ///
  /// # Security
  /// The returned bytes contain sensitive key material (including the private key).
  /// The caller is responsible for securely zeroing these bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side to ensure automatic zeroing.
  Uint8List serialize();

  /// Sign an alternate identity key.
  ///
  /// This is used in the multi-device protocol to link devices.
  Uint8List signAlternateIdentity({required PublicKey otherIdentity});
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PrivateKey>>
abstract class PrivateKey implements RustOpaqueInterface {
  /// Perform X25519 key agreement with a public key.
  ///
  /// # Security
  /// The returned shared secret is highly sensitive cryptographic material.
  /// The caller is responsible for securely zeroing these bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side to ensure automatic zeroing.
  Uint8List agree({required PublicKey publicKey});

  /// Create a copy of this private key.
  ///
  /// # Security
  /// This duplicates sensitive secret key material into a second independent
  /// object. Each copy holds the secret in native memory until it is dropped,
  /// so every copy must be handled with the same care as the original.
  /// In security-critical applications, call `dispose()` on the Dart side of
  /// each copy as soon as it is no longer needed rather than waiting for the
  /// garbage collector, and avoid making copies you do not need.
  PrivateKey cloneKey();

  /// Deserialize a private key from bytes.
  ///
  /// # Security
  /// The input bytes are securely zeroized after deserialization.
  static PrivateKey deserialize({required List<int> bytes}) =>
      RustLib.instance.api.crateApiKeysPrivateKeyDeserialize(bytes: bytes);

  /// Generate a new random private key.
  static PrivateKey generate() =>
      RustLib.instance.api.crateApiKeysPrivateKeyGenerate();

  /// Get the public key corresponding to this private key.
  PublicKey getPublicKey();

  /// Serialize this private key to bytes.
  ///
  /// # Security
  /// The returned bytes contain sensitive key material. The caller is responsible
  /// for securely zeroing these bytes when done. Consider using `SecureBytes.wrap()`
  /// on the Dart side to ensure automatic zeroing.
  Uint8List serialize();

  /// Sign a message with this private key.
  Uint8List sign({required List<int> message});
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PublicKey>>
abstract class PublicKey implements RustOpaqueInterface {
  /// Create a copy of this public key.
  PublicKey cloneKey();

  /// Compare this public key with another.
  ///
  /// Comparison is performed lexicographically on the serialized bytes.
  int compare({required PublicKey other});

  /// Deserialize a public key from bytes.
  static PublicKey deserialize({required List<int> bytes}) =>
      RustLib.instance.api.crateApiKeysPublicKeyDeserialize(bytes: bytes);

  /// Check if this public key equals another.
  bool equals({required PublicKey other});

  /// Get the raw public key bytes without the type prefix.
  Uint8List getPublicKeyBytes();

  /// Serialize this public key to bytes.
  Uint8List serialize();

  /// Verify a signature on a message.
  bool verify({required List<int> message, required List<int> signature});
}
