// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_native`, `from_native`, `from_native`, `from_native`, `native`, `native`, `native`, `native`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KyberKeyPair>>
abstract class KyberKeyPair implements RustOpaqueInterface {
  /// Clone this Kyber key pair.
  KyberKeyPair cloneKey();

  /// Generate a new random Kyber key pair.
  static KyberKeyPair generate() =>
      RustLib.instance.api.crateApiKyberKyberKeyPairGenerate();

  /// Get the public key from this key pair.
  KyberPublicKey getPublicKey();

  /// Get the secret key from this key pair.
  ///
  /// # Security
  /// The returned key contains sensitive secret key material. When serialized,
  /// the caller is responsible for securely zeroing those bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side after serialization.
  KyberSecretKey getSecretKey();
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KyberPreKeyRecord>>
abstract class KyberPreKeyRecord implements RustOpaqueInterface {
  /// Clone this Kyber pre-key record.
  KyberPreKeyRecord cloneRecord();

  /// Create a new Kyber pre-key record.
  static KyberPreKeyRecord create({
    required int id,
    required BigInt timestamp,
    required KyberKeyPair keyPair,
    required List<int> signature,
  }) => RustLib.instance.api.crateApiKyberKyberPreKeyRecordCreate(
    id: id,
    timestamp: timestamp,
    keyPair: keyPair,
    signature: signature,
  );

  /// Deserialize a Kyber pre-key record from bytes.
  ///
  /// # Security
  /// The input bytes are securely zeroized after deserialization.
  static KyberPreKeyRecord deserialize({required List<int> bytes}) => RustLib
      .instance
      .api
      .crateApiKyberKyberPreKeyRecordDeserialize(bytes: bytes);

  /// Get the key pair from this Kyber pre-key record.
  KyberKeyPair getKeyPair();

  /// Get the public key from this Kyber pre-key record.
  KyberPublicKey getPublicKey();

  /// Get the secret key from this Kyber pre-key record.
  ///
  /// # Security
  /// The returned key contains sensitive secret key material. When serialized,
  /// the caller is responsible for securely zeroing those bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side after serialization.
  KyberSecretKey getSecretKey();

  /// Get the ID of this Kyber pre-key record.
  int id();

  /// Serialize this Kyber pre-key record to bytes.
  ///
  /// # Security
  /// The returned bytes contain sensitive key material (including the secret key).
  /// The caller is responsible for securely zeroing these bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side to ensure automatic zeroing.
  Uint8List serialize();

  /// Get the signature of this Kyber pre-key record.
  Uint8List signature();

  /// Get the timestamp of this Kyber pre-key record.
  BigInt timestamp();
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KyberPublicKey>>
abstract class KyberPublicKey implements RustOpaqueInterface {
  /// Clone this Kyber public key.
  KyberPublicKey cloneKey();

  /// Deserialize a Kyber public key from bytes.
  static KyberPublicKey deserialize({required List<int> bytes}) =>
      RustLib.instance.api.crateApiKyberKyberPublicKeyDeserialize(bytes: bytes);

  /// Check if this Kyber public key equals another.
  bool equals({required KyberPublicKey other});

  /// Serialize this Kyber public key to bytes.
  Uint8List serialize();
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KyberSecretKey>>
abstract class KyberSecretKey implements RustOpaqueInterface {
  /// Clone this Kyber secret key.
  KyberSecretKey cloneKey();

  /// Deserialize a Kyber secret key from bytes.
  ///
  /// # Security
  /// The input bytes are securely zeroized after deserialization.
  static KyberSecretKey deserialize({required List<int> bytes}) =>
      RustLib.instance.api.crateApiKyberKyberSecretKeyDeserialize(bytes: bytes);

  /// Serialize this Kyber secret key to bytes.
  ///
  /// # Security
  /// The returned bytes contain sensitive secret key material.
  /// The caller is responsible for securely zeroing these bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side to ensure automatic zeroing.
  Uint8List serialize();
}
