// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_native`, `native`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DecryptionErrorMessage>>
abstract class DecryptionErrorMessage implements RustOpaqueInterface {
  /// Create a copy of this message.
  DecryptionErrorMessage cloneMessage();

  /// Deserialize a decryption error message from bytes.
  static DecryptionErrorMessage deserialize({required List<int> bytes}) =>
      RustLib.instance.api.crateApiMessageDecryptionErrorMessageDeserialize(
        bytes: bytes,
      );

  /// Get the device ID of the original sender.
  int deviceId();

  /// Extract a decryption error message from serialized content.
  static DecryptionErrorMessage extractFromSerializedContent({
    required List<int> bytes,
  }) => RustLib.instance.api
      .crateApiMessageDecryptionErrorMessageExtractFromSerializedContent(
        bytes: bytes,
      );

  /// Create a decryption error message for a failed original message.
  static DecryptionErrorMessage forOriginalMessage({
    required List<int> originalBytes,
    required int messageType,
    required BigInt timestamp,
    required int originalSenderDeviceId,
  }) => RustLib.instance.api
      .crateApiMessageDecryptionErrorMessageForOriginalMessage(
        originalBytes: originalBytes,
        messageType: messageType,
        timestamp: timestamp,
        originalSenderDeviceId: originalSenderDeviceId,
      );

  /// Get the ratchet key from the failed message, if available.
  ///
  /// Returns the serialized public key bytes, or None if not available.
  Uint8List? ratchetKey();

  /// Serialize this message to bytes.
  Uint8List serialize();

  /// Get the timestamp of the original message.
  BigInt timestamp();
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SignalMessage>>
abstract class SignalMessage implements RustOpaqueInterface {
  /// Get the encrypted message body (ciphertext).
  Uint8List body();

  /// Create a copy of this message.
  SignalMessage cloneMessage();

  /// Get the message counter.
  int counter();

  /// Deserialize a SignalMessage from bytes.
  static SignalMessage deserialize({required List<int> data}) =>
      RustLib.instance.api.crateApiMessageSignalMessageDeserialize(data: data);

  /// Get the Signal Protocol message version.
  int messageVersion();

  /// Get the Post-Quantum ratchet state, if present.
  Uint8List? pqRatchet();

  /// Get the sender's current ratchet public key (serialized).
  Uint8List senderRatchetKey();

  /// Serialize the message to bytes.
  Uint8List serialize();

  /// Verify the MAC on this message.
  ///
  /// Takes the sender's and recipient's protocol addresses (name + device id),
  /// the serialized public keys for the sender and receiver identity keys, and
  /// the MAC key. If the message includes embedded addresses, they are also
  /// verified against the supplied addresses for backward compatibility.
  bool verifyMac({
    required String senderAddressName,
    required int senderAddressDeviceId,
    required String recipientAddressName,
    required int recipientAddressDeviceId,
    required List<int> senderIdentityKey,
    required List<int> receiverIdentityKey,
    required List<int> macKey,
  });
}
