// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'keys.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_native`, `native`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PreKeyRecord>>
abstract class PreKeyRecord implements RustOpaqueInterface {
  /// Deserialize a pre-key record from bytes.
  static PreKeyRecord deserialize({required List<int> bytes}) =>
      RustLib.instance.api.crateApiPrekeyPreKeyRecordDeserialize(bytes: bytes);

  /// Get the pre-key ID.
  int id();

  /// Create a new pre-key record.
  ///
  /// # Arguments
  /// * `id` - The pre-key identifier
  /// * `public_key` - The public key
  /// * `private_key` - The private key
  factory PreKeyRecord({
    required int id,
    required PublicKey publicKey,
    required PrivateKey privateKey,
  }) => RustLib.instance.api.crateApiPrekeyPreKeyRecordNew(
    id: id,
    publicKey: publicKey,
    privateKey: privateKey,
  );

  /// Get the private key.
  Uint8List privateKey();

  /// Get the public key.
  Uint8List publicKey();

  /// Serialize this pre-key record to bytes.
  Uint8List serialize();
}
