// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `sealed_sender_decrypt_inner`, `sealed_sender_encrypt_inner`

/// Validate a sender certificate.
///
/// Returns true if valid, throws an error if invalid or expired.
bool validateSenderCertificate({
  required List<int> certificate,
  required List<int> trustRoot,
  required BigInt timestamp,
}) => RustLib.instance.api.crateApiSealedSenderValidateSenderCertificate(
  certificate: certificate,
  trustRoot: trustRoot,
  timestamp: timestamp,
);

/// Get the sender name from a sender certificate.
String senderCertificateGetSenderName({required List<int> certificate}) =>
    RustLib.instance.api.crateApiSealedSenderSenderCertificateGetSenderName(
      certificate: certificate,
    );

/// Get the sender device ID from a sender certificate.
int senderCertificateGetSenderDeviceId({required List<int> certificate}) =>
    RustLib.instance.api.crateApiSealedSenderSenderCertificateGetSenderDeviceId(
      certificate: certificate,
    );

/// Get the sender public key from a sender certificate.
Uint8List senderCertificateGetKey({required List<int> certificate}) => RustLib
    .instance
    .api
    .crateApiSealedSenderSenderCertificateGetKey(certificate: certificate);

/// Get the expiration timestamp from a sender certificate.
BigInt senderCertificateGetExpiration({required List<int> certificate}) =>
    RustLib.instance.api.crateApiSealedSenderSenderCertificateGetExpiration(
      certificate: certificate,
    );

/// Create a server certificate for testing.
///
/// # Parameters
/// - `key_id` - A unique identifier for this server certificate
/// - `server_public_key` - The server's public key to be certified
/// - `trust_root_private_key` - The trust root's private key for signing
///
/// # Returns
/// The serialized server certificate.
Uint8List createServerCertificate({
  required int keyId,
  required List<int> serverPublicKey,
  required List<int> trustRootPrivateKey,
}) => RustLib.instance.api.crateApiSealedSenderCreateServerCertificate(
  keyId: keyId,
  serverPublicKey: serverPublicKey,
  trustRootPrivateKey: trustRootPrivateKey,
);

/// Create a sender certificate for testing.
///
/// # Parameters
/// - `sender_uuid` - The sender's UUID (e.g., "abc-123")
/// - `sender_device_id` - The sender's device ID
/// - `sender_identity_key` - The sender's identity public key
/// - `expiration` - Certificate expiration timestamp (milliseconds since epoch)
/// - `server_certificate` - The server certificate (serialized)
/// - `server_private_key` - The server's private key for signing
///
/// # Returns
/// The serialized sender certificate.
Uint8List createSenderCertificate({
  required String senderUuid,
  required int senderDeviceId,
  required List<int> senderIdentityKey,
  required BigInt expiration,
  required List<int> serverCertificate,
  required List<int> serverPrivateKey,
}) => RustLib.instance.api.crateApiSealedSenderCreateSenderCertificate(
  senderUuid: senderUuid,
  senderDeviceId: senderDeviceId,
  senderIdentityKey: senderIdentityKey,
  expiration: expiration,
  serverCertificate: serverCertificate,
  serverPrivateKey: serverPrivateKey,
);

/// Encrypt a message using Sealed Sender (anonymous delivery).
///
/// # Callbacks
/// - `load_session(name, device_id)` - Load existing session (required)
/// - `store_session(name, device_id, bytes)` - Store the updated session
/// - `get_identity_key_pair()` - Get our identity key pair
/// - `get_local_registration_id()` - Get our registration ID
///
/// # Parameters
/// - `recipient_name` - Recipient's user identifier
/// - `recipient_device_id` - Recipient's device ID
/// - `plaintext` - The message to encrypt
/// - `sender_certificate` - Our sender certificate (serialized)
Future<SealedSenderEncryptResult> sealedSenderEncryptWithCallbacks({
  required String recipientName,
  required int recipientDeviceId,
  required List<int> plaintext,
  required List<int> senderCertificate,
  required FutureOr<Uint8List?> Function(String, int) loadSession,
  required FutureOr<void> Function(String, int, Uint8List) storeSession,
  required FutureOr<Uint8List> Function() getIdentityKeyPair,
  required FutureOr<int> Function() getLocalRegistrationId,
}) => RustLib.instance.api.crateApiSealedSenderSealedSenderEncryptWithCallbacks(
  recipientName: recipientName,
  recipientDeviceId: recipientDeviceId,
  plaintext: plaintext,
  senderCertificate: senderCertificate,
  loadSession: loadSession,
  storeSession: storeSession,
  getIdentityKeyPair: getIdentityKeyPair,
  getLocalRegistrationId: getLocalRegistrationId,
);

/// Decrypt a Sealed Sender message.
///
/// # Callbacks
/// SessionStore:
/// - `load_session(name, device_id)` - Load existing session
/// - `store_session(name, device_id, bytes)` - Store session
///
/// IdentityKeyStore:
/// - `get_identity_key_pair()` - Get our identity key pair
/// - `get_local_registration_id()` - Get our registration ID
/// - `save_identity(name, device_id, identity_bytes)` - Save sender's identity
///
/// PreKeyStores:
/// - `load_signed_pre_key(id)` - Load signed pre-key
/// - `load_pre_key(id)` - Load one-time pre-key
/// - `load_kyber_pre_key(id)` - Load Kyber pre-key
///
/// # Parameters
/// - `ciphertext` - The sealed sender ciphertext
/// - `trust_root` - Server's trust root public key
/// - `timestamp` - Current timestamp for certificate validation
Future<SealedSenderDecryptResult> sealedSenderDecryptWithCallbacks({
  required List<int> ciphertext,
  required List<int> trustRoot,
  required BigInt timestamp,
  required FutureOr<Uint8List?> Function(String, int) loadSession,
  required FutureOr<void> Function(String, int, Uint8List) storeSession,
  required FutureOr<Uint8List> Function() getIdentityKeyPair,
  required FutureOr<int> Function() getLocalRegistrationId,
  required FutureOr<void> Function(String, int, Uint8List) saveIdentity,
  required FutureOr<Uint8List?> Function(int) loadSignedPreKey,
  required FutureOr<Uint8List?> Function(int) loadPreKey,
  required FutureOr<Uint8List?> Function(int) loadKyberPreKey,
}) => RustLib.instance.api.crateApiSealedSenderSealedSenderDecryptWithCallbacks(
  ciphertext: ciphertext,
  trustRoot: trustRoot,
  timestamp: timestamp,
  loadSession: loadSession,
  storeSession: storeSession,
  getIdentityKeyPair: getIdentityKeyPair,
  getLocalRegistrationId: getLocalRegistrationId,
  saveIdentity: saveIdentity,
  loadSignedPreKey: loadSignedPreKey,
  loadPreKey: loadPreKey,
  loadKyberPreKey: loadKyberPreKey,
);

/// Result of sealed sender decryption.
class SealedSenderDecryptResult {
  /// The decrypted plaintext.
  final Uint8List plaintext;

  /// The sender's name (UUID).
  final String senderName;

  /// The sender's device ID.
  final int senderDeviceId;

  /// The sender's identity key (for verification).
  final Uint8List senderIdentityKey;

  /// The updated or new session record.
  final Uint8List sessionRecord;

  /// Pre-key ID to remove (if a one-time pre-key was used).
  final int? preKeyToRemove;

  const SealedSenderDecryptResult({
    required this.plaintext,
    required this.senderName,
    required this.senderDeviceId,
    required this.senderIdentityKey,
    required this.sessionRecord,
    this.preKeyToRemove,
  });

  @override
  int get hashCode =>
      plaintext.hashCode ^
      senderName.hashCode ^
      senderDeviceId.hashCode ^
      senderIdentityKey.hashCode ^
      sessionRecord.hashCode ^
      preKeyToRemove.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SealedSenderDecryptResult &&
          runtimeType == other.runtimeType &&
          plaintext == other.plaintext &&
          senderName == other.senderName &&
          senderDeviceId == other.senderDeviceId &&
          senderIdentityKey == other.senderIdentityKey &&
          sessionRecord == other.sessionRecord &&
          preKeyToRemove == other.preKeyToRemove;
}

/// Result of sealed sender encryption.
class SealedSenderEncryptResult {
  /// The sealed sender ciphertext.
  final Uint8List ciphertext;

  /// The updated session record.
  final Uint8List sessionRecord;

  const SealedSenderEncryptResult({
    required this.ciphertext,
    required this.sessionRecord,
  });

  @override
  int get hashCode => ciphertext.hashCode ^ sessionRecord.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SealedSenderEncryptResult &&
          runtimeType == other.runtimeType &&
          ciphertext == other.ciphertext &&
          sessionRecord == other.sessionRecord;
}
