import 'package:test/test.dart';

import '../../scripts/src/release_frb.dart';

void main() {
  group('stampFrbHighlight', () {
    test('replaces an existing libsignal_frb highlight in place', () {
      const changelog = '''
## [Unreleased]

### For Users

#### ✨ Highlights

- **libsignal v0.97.3** — internal/dependency update, no public-API impact
- **libsignal_frb v5.1.0** — Rust FFI bindings

#### Changed

- Update libsignal native library to v0.97.3

## [6.0.0] - 2026-07-14
''';
      final result = stampFrbHighlight(changelog, '5.2.0');
      expect(result, contains('**libsignal_frb v5.2.0** — Rust FFI bindings'));
      expect(result, isNot(contains('libsignal_frb v5.1.0')));
      // The libsignal highlight is untouched.
      expect(result, contains('**libsignal v0.97.3**'));
    });

    test('inserts after the last highlight when no frb line exists', () {
      const changelog = '''
## [Unreleased]

### For Users

#### ✨ Highlights

- **libsignal v0.97.4** — internal/dependency update, no public-API impact

#### Changed

- Update libsignal native library to v0.97.4

## [6.0.0] - 2026-07-14
''';
      final result = stampFrbHighlight(changelog, '5.2.0');
      final lines = result.split('\n');
      final libsignalIdx = lines.indexWhere(
        (l) => l.contains('**libsignal v0.97.4**'),
      );
      final frbIdx = lines.indexWhere(
        (l) => l.contains('**libsignal_frb v5.2.0**'),
      );
      expect(libsignalIdx, greaterThanOrEqualTo(0));
      expect(
        frbIdx,
        equals(libsignalIdx + 1),
        reason: 'frb line should follow the libsignal highlight',
      );
      // Did not leak into the released section.
      final releasedIdx = lines.indexWhere((l) => l.startsWith('## [6.0.0]'));
      expect(frbIdx, lessThan(releasedIdx));
    });

    test('creates an [Unreleased] section when none exists', () {
      const changelog = '''
# Changelog

## [6.0.0] - 2026-07-14

### For Users

- something
''';
      final result = stampFrbHighlight(changelog, '5.2.0');
      expect(result, contains('## [Unreleased]'));
      expect(result, contains('#### ✨ Highlights'));
      expect(result, contains('**libsignal_frb v5.2.0** — Rust FFI bindings'));
      // Unreleased must come before the first released version.
      final lines = result.split('\n');
      expect(
        lines.indexWhere((l) => l.startsWith('## [Unreleased]')),
        lessThan(lines.indexWhere((l) => l.startsWith('## [6.0.0]'))),
      );
    });

    test('is idempotent across repeated runs (replace, not duplicate)', () {
      const changelog = '''
## [Unreleased]

### For Users

#### ✨ Highlights

- **libsignal v0.97.4** — internal/dependency update, no public-API impact

## [6.0.0] - 2026-07-14
''';
      final once = stampFrbHighlight(changelog, '5.2.0');
      final twice = stampFrbHighlight(once, '5.2.0');
      final count = '**libsignal_frb v5.2.0**'.allMatches(twice).length;
      expect(count, equals(1), reason: 'must not accumulate duplicate lines');
    });

    test('creates the ### For Users parent when stamping into an empty '
        '[Unreleased] (no orphan Highlights block)', () {
      // A fresh [Unreleased] left by a package release: heading + blank only.
      const changelog = '''
## [Unreleased]

## [6.0.0] - 2026-07-14

### For Users

- something
''';
      final result = stampFrbHighlight(changelog, '5.3.0');
      final lines = result.split('\n');
      final unreleasedIdx = lines.indexWhere(
        (l) => l.startsWith('## [Unreleased]'),
      );
      final forUsersIdx = lines.indexWhere(
        (l) => l.startsWith('### For Users'),
      );
      final highlightsIdx = lines.indexWhere(
        (l) => l.startsWith('#### ✨ Highlights'),
      );
      final releasedIdx = lines.indexWhere((l) => l.startsWith('## [6.0.0]'));
      // The stamped Highlights block sits under a For Users heading that is
      // itself inside the [Unreleased] section (before the released heading).
      expect(unreleasedIdx, lessThan(forUsersIdx));
      expect(forUsersIdx, lessThan(highlightsIdx));
      expect(highlightsIdx, lessThan(releasedIdx));
      expect(result, contains('**libsignal_frb v5.3.0** — Rust FFI bindings'));
    });
  });

  group('bumpCargoLockVersion', () {
    const lock = '''
# This file is automatically @generated by Cargo.

[[package]]
name = "libsignal_frb"
version = "5.1.0"
dependencies = [
 "flutter_rust_bridge",
]

[[package]]
name = "other_crate"
version = "5.1.0"
''';

    test('bumps only the named crate stanza, not a coincidental match', () {
      final result = bumpCargoLockVersion(lock, 'libsignal_frb', '5.2.0');
      expect(result, contains('name = "libsignal_frb"\nversion = "5.2.0"'));
      // A different package that happens to share the old version is untouched.
      expect(result, contains('name = "other_crate"\nversion = "5.1.0"'));
    });

    test('throws when the crate stanza is absent', () {
      expect(
        () => bumpCargoLockVersion(lock, 'missing_crate', '5.2.0'),
        throwsA(isA<Exception>()),
      );
    });
  });
}
